#
# Script to create all of the 2014 Horses tables
#
# The Horses tables are:
#    TABLE 3-1: NUMBER OF LIVESTOCK BY TYPE OF ANIMAL, ZONE, AND REGION
#    TABLE 3-5: NUMBER OF HORSES AND DONKEYS BY AGE AND SEX OF ANIMAL, ZONE, AND REGION
#    TABLE 3-10: HORSES AGED 3 YEARS AND OLDER BY SEX, PURPOSE, ZONE, AND REGION
#    TABLE 3–19d: ESTIMATED NUMBERS OF BIRTHS, PURCHASES, AND ACQUIRED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Horses
#    TABLE 3–20d: ESTIMATED NUMBERS OF SALES, SLAUGHTERS, DEATHS, AND OFFERED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Horses
#    TABLE 3-26a: ESTIMATED NUMBER OF LIVESTOCK DIED FROM DISEASE BY ZONE AND REGION
#    TABLE 3-26b: ESTIMATED NUMBER OF LIVESTOCK DIED FROM OTHER CAUSES BY ZONE AND REGION
#    TABLE 3-27d: NUMBER OF HOLDINGS BY SIZES OF HORSES AND DONKEYS
#
# echo "TABLE 3-1: NUMBER OF LIVESTOCK BY TYPE OF ANIMAL, ZONE, AND REGION"
# ./pdfETHCSApipeline.sh 2014-Livestock.pdf pages.pdf table3-1.csv 44 45 tmpTable.csv 2014_Table_3-1.csv 2014
echo "TABLE 3-5: NUMBER OF HORSES AND DONKEYS BY AGE AND SEX OF ANIMAL, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2014-Livestock.pdf pages.pdf table3-5.csv 52 53 tmpTable.csv 2014_Table_3-5.csv 2014
echo "TABLE 3-10: HORSES AGED 3 YEARS AND OLDER BY SEX, PURPOSE, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2014-Livestock.pdf pages.pdf table3-10.csv 62 63 tmpTable.csv 2014_Table_3-10.csv 2014
echo "TABLE 3–19d: ESTIMATED NUMBERS OF BIRTHS, PURCHASES, AND ACQUIRED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Horses"
./pdfETHCSApipeline.sh 2014-Livestock.pdf pages.pdf table3-19d.csv 92 93 tmpTable.csv 2014_Table_3-19d.csv 2014
echo "TABLE 3–20d: ESTIMATED NUMBERS OF SALES, SLAUGHTERS, DEATHS, AND OFFERED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Horses"
./pdfETHCSApipeline.sh 2014-Livestock.pdf pages.pdf table3-20d.csv 108 109 tmpTable.csv 2014_Table_3-20d.csv 2014
# echo "TABLE 3-26a: ESTIMATED NUMBER OF LIVESTOCK DIED FROM DISEASE BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2014-Livestock.pdf pages.pdf table3-26a.csv 138 139 tmpTable.csv 2014_Table_3-26a.csv 2014
# echo "TABLE 3-26b: ESTIMATED NUMBER OF LIVESTOCK DIED FROM OTHER CAUSES BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2014-Livestock.pdf pages.pdf table3-26b.csv 140 141 tmpTable.csv 2014_Table_3-26b.csv 2014
echo "TABLE 3-27d:NUMBER OF HOLDINGS BY SIZES OF HORSES AND DONKEYS"
./pdfETHCSApipeline.sh 2014-Livestock.pdf pages.pdf table3-27d.csv 148 149 tmpTable.csv 2014_Table_3-27d.csv 2014
echo "2014 Horses tables complete"
