#
# Script to create all of the 2009 Mules tables
#
# The Mules tables are:
#    TABLE 3-1: NUMBER OF LIVESTOCK BY TYPE OF ANIMAL, ZONE, AND REGION
#    TABLE 3-6: NUMBER OF MULES AND CAMELS BY AGE AND SEX OF ANIMAL, ZONE, AND REGION
#    TABLE 3-12: MULES AGED 3 YEARS AND OLDER BY SEX, PURPOSE, ZONE, AND REGION
#    TABLE 3–19f: ESTIMATED NUMBERS OF BIRTHS, PURCHASES, AND ACQUIRED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Mules
#    TABLE 3–20f: ESTIMATED NUMBERS OF SALES, SLAUGHTERS, DEATHS, AND OFFERED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Mules
#    TABLE 3-26a: ESTIMATED NUMBER OF LIVESTOCK DIED FROM DISEASE BY ZONE AND REGION
#    TABLE 3-26b: ESTIMATED NUMBER OF LIVESTOCK DIED FROM OTHER CAUSES BY ZONE AND REGION
#    TABLE 3-27e: NUMBER OF HOLDINGS BY SIZES OF MULES AND CAMELS
#
# echo "TABLE 3-1: NUMBER OF LIVESTOCK BY TYPE OF ANIMAL, ZONE, AND REGION"
# ./pdfETHCSApipeline.sh 2009-Livestock.pdf pages.pdf table3-1.csv 40 40 tmpTable.csv 2009_Table_3-1.csv 2009
# echo "TABLE 3-6: NUMBER OF MULES AND CAMELS BY AGE AND SEX OF ANIMAL, ZONE, AND REGION"
# ./pdfETHCSApipeline.sh 2009-Livestock.pdf pages.pdf table3-6.csv 42 42 tmpTable.csv 2009_Table_3-6.csv 2009
echo "TABLE 3-12: Mules AGED 3 YEARS AND OLDER BY SEX, PURPOSE, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2009-Livestock.pdf pages.pdf table3-12.csv 45 45 tmpTable.csv 2009_Table_3-12.csv 2009
echo "TABLE 3–19f: ESTIMATED NUMBERS OF BIRTHS, PURCHASES, AND ACQUIRED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Mules"
./pdfETHCSApipeline.sh 2009-Livestock.pdf pages.pdf table3-19f.csv 53 53 tmpTable.csv 2009_Table_3-19f.csv 2009
echo "TABLE 3–20f: ESTIMATED NUMBERS OF SALES, SLAUGHTERS, DEATHS, AND OFFERED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Mules"
./pdfETHCSApipeline.sh 2009-Livestock.pdf pages.pdf table3-20f.csv 57 57 tmpTable.csv 2009_Table_3-20f.csv 2009
# echo "TABLE 3-26a: ESTIMATED NUMBER OF LIVESTOCK DIED FROM DISEASE BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2009-Livestock.pdf pages.pdf table3-26a.csv 63 63 tmpTable.csv 2009_Table_3-26a.csv 2009
# echo "TABLE 3-26b: ESTIMATED NUMBER OF LIVESTOCK DIED FROM OTHER CAUSES BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2009-Livestock.pdf pages.pdf table3-26b.csv 64 64 tmpTable.csv 2009_Table_3-26b.csv 2009
# echo "TABLE 3-27e: NUMBER OF HOLDINGS BY SIZES OF MULES AND CAMELS"
# ./pdfETHCSApipeline.sh 2009-Livestock.pdf pages.pdf table3-27e.csv 66 66 tmpTable.csv 2009_Table_3-27e.csv 2009
echo "2009 Mules tables complete"
