#
# Script to create all of the 2004 Mules tables
#
# The Mules tables are:
#    TABLE 3-1: NUMBER OF LIVESTOCK BY TYPE OF ANIMAL, ZONE, AND REGION
#    TABLE 3-6: NUMBER OF MULES AND CAMELS BY AGE AND SEX OF ANIMAL, ZONE, AND REGION
#    TABLE 3-12: MULES AGED 3 YEARS AND OLDER BY SEX, PURPOSE, ZONE, AND REGION
#    TABLE 3-17a: ESTIMATED NUMBER OF NEWBORN LIVESTOCK DURING THE REFERENCE PERIOD BY TYPE, ZONE AND REGION - TOTAL
#    TABLE 3-17b: ESTIMATED NUMBER OF NEWBORN LIVESTOCK DURING THE REFERENCE PERIOD BY TYPE, ZONE AND REGION - MALE
#    TABLE 3-17c: ESTIMATED NUMBER OF NEWBORN LIVESTOCK DURING THE REFERENCE PERIOD BY TYPE, ZONE AND REGION - FEMALE
#    TABLE 3-25a: ESTIMATED NUMBER OF LIVESTOCK DIED FROM DISEASE BY ZONE AND REGION
#    TABLE 3-25b: ESTIMATED NUMBER OF LIVESTOCK DIED FROM OTHER REASONS BY ZONE AND REGION
#    TABLE 3-26e: NUMBER OF HOLDINGS BY SIZES OF MULES AND CAMELS
#
# echo "TABLE 3-1: NUMBER OF LIVESTOCK BY TYPE OF ANIMAL, ZONE, AND REGION"
# ./pdfETHCSApipeline.sh 2004-Livestock.pdf pages.pdf table3-1.csv 37 38 tmpTable.csv 2004_Table_3-1.csv 2004
# echo "TABLE 3-6: NUMBER OF MULES AND CAMELS BY AGE AND SEX OF ANIMAL, ZONE, AND REGION"
# ./pdfETHCSApipeline.sh 2004-Livestock.pdf pages.pdf table3-6.csv 47 48 tmpTable.csv 2004_Table_3-6.csv 2004
echo "TABLE 3-12: Mules AGED 3 YEARS AND OLDER BY SEX, PURPOSE, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2004-Livestock.pdf pages.pdf table3-12.csv 59 60 tmpTable.csv 2004_Table_3-12.csv 2004
# echo "TABLE 3-17a: ESTIMATED NUMBER OF NEWBORN LIVESTOCK DURING THE REFERENCE PERIOD BY TYPE, ZONE AND REGION - TOTAL"
# ./pdfETHCSApipeline.sh 2004-Livestock.pdf pages.pdf table3-17a.csv 69 70 tmpTable.csv 2004_Table_3-17a.csv 2004
# echo "TABLE 3-17b: ESTIMATED NUMBER OF NEWBORN LIVESTOCK DURING THE REFERENCE PERIOD BY TYPE, ZONE AND REGION - MALE"
# ./pdfETHCSApipeline.sh 2004-Livestock.pdf pages.pdf table3-17b.csv 71 72 tmpTable.csv 2004_Table_3-17b.csv 2004
# echo "TABLE 3-17c: ESTIMATED NUMBER OF NEWBORN LIVESTOCK DURING THE REFERENCE PERIOD BY TYPE, ZONE AND REGION - FEMALE"
# ./pdfETHCSApipeline.sh 2004-Livestock.pdf pages.pdf table3-17c.csv 73 74 tmpTable.csv 2004_Table_3-17c.csv 2004
# echo "TABLE 3-25a: ESTIMATED NUMBER OF LIVESTOCK DIED FROM DISEASE BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2004-Livestock.pdf pages.pdf table3-25a.csv 93 94 tmpTable.csv 2004_Table_3-25a.csv 2004
# echo "TABLE 3-25b: ESTIMATED NUMBER OF LIVESTOCK DIED FROM OTHER REASONS BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2004-Livestock.pdf pages.pdf table3-25b.csv 95 96 tmpTable.csv 2004_Table_3-25b.csv 2004
# echo "TABLE 3-26e: NUMBER OF HOLDINGS BY SIZES OF MULES AND CAMELS"
# ./pdfETHCSApipeline.sh 2004-Livestock.pdf pages.pdf table3-26e.csv 105 106 tmpTable.csv 2004_Table_3-26e.csv 2004
echo "2004 Mules tables complete"
