#
# Script to create all of the 2018 Goat tables
#
# The Goats tables are:
#    TABLE 3-1: NUMBER OF LIVESTOCK BY TYPE OF ANIMAL, AND REGION
#    TABLE 3-4: NUMBER OF GOATS BY AGE AND SEX OF ANIMAL AND REGION
#    TABLE 3-9: GOATS AGED 2 YEARS AND OLDER BY SEX, PURPOSE AND REGION
#    TABLE 3-16: NUMBER OF GOATS BY SEX, BREED AND REGION
#    TABLE 3–19c: ESTIMATED NUMBERS OF BIRTHS, PURCHASES, AND ACQUIRED ANIMALS DURING THE REFERENCE PERIOD AND REGION - Goats
#    TABLE 3–20c: ESTIMATED NUMBERS OF SALES, SLAUGHTERS, DEATHS, AND OFFERED ANIMALS DURING THE REFERENCE PERIOD AND REGION - GOATS
#    TABLE 3-23c: ESTIMATED NUMBER OF VACCINATED LIVESTOCK AND REGION - Goats
#    TABLE 3-24: ESTIMATED NUMBER OF LIVESTOCK AFFLICTED/DISEASED AND REGION
#    TABLE 3-25: ESTIMATED NUMBER OF LIVESTOCK TREATED AND REGION
#    TABLE 3-26a: ESTIMATED NUMBER OF LIVESTOCK DIED FROM DISEASE AND REGION
#    TABLE 3-26b: ESTIMATED NUMBER OF LIVESTOCK DIED FROM OTHER CAUSES AND REGION
#    TABLE 3-27c: NUMBER OF HOLDINGS BY SIZE OF GOATS
#
# echo "TABLE 3-1: NUMBER OF LIVESTOCK BY TYPE OF ANIMAL AND REGION"
# ./pdfETHCSApipeline.sh 2018-Livestock.pdf pages.pdf table3-1.csv 43 43 tmpTable.csv 2018_Table_3-1.csv 2018
echo "TABLE 3-4: NUMBER OF GOATS BY AGE AND SEX OF ANIMAL AND REGION"
./pdfETHCSApipeline.sh 2018-Livestock.pdf pages.pdf table3-4.csv 44 44 tmpTable.csv 2018_Table_3-4.csv 2018
echo "TABLE 3-9: GOATS AGED 2 YEARS AND OLDER BY SEX, PURPOSE AND REGION"
./pdfETHCSApipeline.sh 2018-Livestock.pdf pages.pdf table3-9.csv 47 47 tmpTable.csv 2018_Table_3-9.csv 2018
echo "TABLE 3-16: NUMBER OF GOATS BY SEX, BREED AND REGION"
./pdfETHCSApipeline.sh 2018-Livestock.pdf pages.pdf table3-16.csv 50 50 tmpTable.csv 2018_Table_3-16.csv 2018
echo "TABLE 3–19c: ESTIMATED NUMBERS OF BIRTHS, PURCHASES, AND ACQUIRED ANIMALS DURING THE REFERENCE PERIOD AND REGION - Goats"
./pdfETHCSApipeline.sh 2018-Livestock.pdf pages.pdf table3-19c.csv 54 54 tmpTable.csv 2018_Table_3-19c.csv 2018
echo "TABLE 3–20c: ESTIMATED NUMBERS OF SALES, SLAUGHTERS, DEATHS, AND OFFERED ANIMALS DURING THE REFERENCE PERIOD AND REGION - GOATS"
./pdfETHCSApipeline.sh 2018-Livestock.pdf pages.pdf table3-20c.csv 58 58 tmpTable.csv 2018_Table_3-20c.csv 2018
echo "TABLE 3-23c: ESTIMATED NUMBER OF VACCINATED LIVESTOCK AND REGION - Goats"
./pdfETHCSApipeline.sh 2018-Livestock.pdf pages.pdf table3-23c.csv 64 64 tmpTable.csv 2018_Table_3-23c.csv 2018
# echo "TABLE 3-24: ESTIMATED NUMBER OF LIVESTOCK AFFLICTED/DISEASED AND REGION"
# ./pdfETHCSApipeline.sh 2018-Livestock.pdf pages.pdf table3-24.csv 66 66 tmpTable.csv 2018_Table_3-24.csv 2018
# echo "TABLE 3-25: ESTIMATED NUMBER OF LIVESTOCK TREATED AND REGION"
# ./pdfETHCSApipeline.sh 2018-Livestock.pdf pages.pdf table3-25.csv 66 66 tmpTable.csv 2018_Table_3-25.csv 2018
# echo "TABLE 3-26a: ESTIMATED NUMBER OF LIVESTOCK DIED FROM DISEASE AND REGION"
# ./pdfETHCSApipeline.sh 2018-Livestock.pdf pages.pdf table3-26a.csv 67 67 tmpTable.csv 2018_Table_3-26a.csv 2018
# echo "TABLE 3-26b: ESTIMATED NUMBER OF LIVESTOCK DIED FROM OTHER CAUSES AND REGION"
# ./pdfETHCSApipeline.sh 2018-Livestock.pdf pages.pdf table3-26b.csv 67 67 tmpTable.csv 2018_Table_3-26b.csv 2018
echo "TABLE 3-27c: NUMBER OF HOLDINGS BY SIZE OF GOATS"
./pdfETHCSApipeline.sh 2018-Livestock.pdf pages.pdf table3-27c.csv 69 69 tmpTable.csv 2018_Table_3-27c.csv 2018
echo "2018 Goats tables complete"
