#
# Script to create all of the 2011 Camels tables
#
# The Camels tables are:
#    TABLE 3-1: NUMBER OF LIVESTOCK BY TYPE OF ANIMAL, ZONE, AND REGION
#    TABLE 3-6: NUMBER OF MULES AND CAMELS BY AGE AND SEX OF ANIMAL, ZONE, AND REGION
#    TABLE 3-13: CAMELS AGED 4 YEARS AND OLDER BY SEX, PURPOSE, ZONE, AND REGION
#    TABLE 3–19g: ESTIMATED NUMBERS OF BIRTHS, PURCHASES, AND ACQUIRED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Camels
#    TABLE 3–20g: ESTIMATED NUMBERS OF SALES, SLAUGHTERS, DEATHS, AND OFFERED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Camels
#    TABLE 3-21: NUMBER OF DAIRY ANIMALS, MILK PRODUCTION, AND LACTATION PERIOD BY ZONE AND REGION
#    TABLE 3-23d: ESTIMATED NUMBER OF VACCINATED LIVESTOCK BY ZONE AND REGION - Draught Animal
#    TABLE 3-24: ESTIMATED NUMBER OF LIVESTOCK AFFLICTED/DISEASED BY ZONE AND REGION
#    TABLE 3-25: ESTIMATED NUMBER OF LIVESTOCK TREATED BY ZONE AND REGION
#    TABLE 3-26a: ESTIMATED NUMBER OF LIVESTOCK DIED FROM DISEASE BY ZONE AND REGION
#    TABLE 3-26b: ESTIMATED NUMBER OF LIVESTOCK DIED FROM OTHER CAUSES BY ZONE AND REGION
#    TABLE 3-27e: NUMBER OF HOLDINGS BY SIZES OF MULES AND CAMELS
#
# echo "TABLE 3-1: NUMBER OF LIVESTOCK BY TYPE OF ANIMAL, ZONE, AND REGION"
# ./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-1.csv 40 41 tmpTable.csv 2011_Table_3-1.csv 2011
echo "TABLE 3-6: NUMBER OF MULES AND CAMELS BY AGE AND SEX OF ANIMAL, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-6.csv 50 51 tmpTable.csv 2011_Table_3-6.csv 2011
echo "TABLE 3-13: CAMELS AGED 4 YEARS AND OLDER BY SEX, PURPOSE, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-13.csv 64 65 tmpTable.csv 2011_Table_3-13.csv 2011
echo "TABLE 3–19g: ESTIMATED NUMBERS OF BIRTHS, PURCHASES, AND ACQUIRED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Camels"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-19g.csv 94 95 tmpTable.csv 2011_Table_3-19g.csv 2011
echo "TABLE 3–20g: ESTIMATED NUMBERS OF SALES, SLAUGHTERS, DEATHS, AND OFFERED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Camels"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-20g.csv 110 111 tmpTable.csv 2011_Table_3-20g.csv 2011
# echo "TABLE 3-21: NUMBER OF DAIRY ANIMALS, MILK PRODUCTION, AND LACTATION PERIOD BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-21.csv 114 115 tmpTable.csv 2011_Table_3-21.csv 2011
echo "TABLE 3-23d: ESTIMATED NUMBER OF VACCINATED LIVESTOCK BY ZONE AND REGION - Draught Animals"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-23d.csv 128 129 tmpTable.csv 2011_Table_3-23d.csv 2011
# echo "TABLE 3-24: ESTIMATED NUMBER OF LIVESTOCK AFFLICTED/DISEASED BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-24.csv 130 131 tmpTable.csv 2011_Table_3-24.csv 2011
# echo "TABLE 3-25: ESTIMATED NUMBER OF LIVESTOCK TREATED BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-25.csv 132 133 tmpTable.csv 2011_Table_3-25.csv 2011
# echo "TABLE 3-26a: ESTIMATED NUMBER OF LIVESTOCK DIED FROM DISEASE BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-26a.csv 134 135 tmpTable.csv 2011_Table_3-26a.csv 2011
# echo "TABLE 3-26b: ESTIMATED NUMBER OF LIVESTOCK DIED FROM OTHER CAUSES BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-26b.csv 136 137 tmpTable.csv 2011_Table_3-26b.csv 2011
echo "TABLE 3-27e: NUMBER OF HOLDINGS BY SIZES OF MULES AND CAMELS"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-27e.csv 146 147 tmpTable.csv 2011_Table_3-27e.csv 2011
echo "2011 Camels tables complete"
