#
# Script to create all of the 2011 Cattle tables
#
# The Cattle tables are:
#    TABLE 3-1: NUMBER OF LIVESTOCK BY TYPE OF ANIMAL, ZONE, AND REGION
#    TABLE 3-2: NUMBER OF CATTLE BY AGE AND SEX OF ANIMAL, ZONE, ZONE, AND REGION
#    TABLE 3-7: CATTLE AGED 3 – 10 YEARS BY SEX, PURPOSE, ZONE, AND REGION
#    TABLE 3-14: NUMBER OF CATTLE BY SEX, BREED, ZONE, AND REGION
#    TABLE 3–19a: ESTIMATED NUMBERS OF BIRTHS, PURCHASES, AND ACQUIRED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Cattle
#    TABLE 3–20a: ESTIMATED NUMBERS OF SALES, SLAUGHTERS, DEATHS, AND OFFERED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Cattle
#    TABLE 3-21: NUMBER OF DAIRY ANIMALS, MILK PRODUCTION, AND LACTATION PERIOD BY ZONE AND REGION
#    TABLE 3-23a: ESTIMATED NUMBER OF VACCINATED LIVESTOCK BY ZONE AND REGION - Cattle
#    TABLE 3-24: ESTIMATED NUMBER OF LIVESTOCK AFFLICTED/DISEASED BY ZONE AND REGION
#    TABLE 3-25: ESTIMATED NUMBER OF LIVESTOCK TREATED BY ZONE AND REGION
#    TABLE 3-26a: ESTIMATED NUMBER OF LIVESTOCK DIED FROM DISEASE BY ZONE AND REGION
#    TABLE 3-26b: ESTIMATED NUMBER OF LIVESTOCK DIED FROM OTHER CAUSES BY ZONE AND REGION
#    TABLE 3-27a: NUMBER OF HOLDINGS BY SIZE OF CATTLE
#
echo "TABLE 3-1: NUMBER OF LIVESTOCK BY TYPE OF ANIMAL, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-1.csv 40 41 tmpTable.csv 2011_Table_3-1.csv 2011
echo "TABLE 3-2: NUMBER OF CATTLE BY AGE AND SEX OF ANIMAL, ZONE, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-2.csv 42 43 tmpTable.csv 2011_Table_3-2.csv 2011
echo "TABLE 3-7: CATTLE AGED 3 – 10 YEARS BY SEX, PURPOSE, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-7.csv 52 53 tmpTable.csv 2011_Table_3-7.csv 2011
echo "TABLE 3-14: NUMBER OF CATTLE BY SEX, BREED, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-14.csv 66 67 tmpTable.csv 2011_Table_3-14.csv 2011
echo "TABLE 3–19a: ESTIMATED NUMBERS OF BIRTHS, PURCHASES, AND ACQUIRED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Cattle"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-19a.csv 82 83 tmpTable.csv 2011_Table_3-19a.csv 2011
echo "TABLE 3–20a: ESTIMATED NUMBERS OF SALES, SLAUGHTERS, DEATHS, AND OFFERED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Cattle"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-20a.csv 98 99 tmpTable.csv 2011_Table_3-20a.csv 2011
echo "TABLE 3-21: NUMBER OF DAIRY ANIMALS, MILK PRODUCTION, AND LACTATION PERIOD BY ZONE AND REGION"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-21.csv 114 115 tmpTable.csv 2011_Table_3-21.csv 2011
echo "TABLE 3-23a: ESTIMATED NUMBER OF VACCINATED LIVESTOCK BY ZONE AND REGION - Cattle"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-23a.csv 122 123 tmpTable.csv 2011_Table_3-23a.csv 2011
echo "TABLE 3-24: ESTIMATED NUMBER OF LIVESTOCK AFFLICTED/DISEASED BY ZONE AND REGION"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-24.csv 130 131 tmpTable.csv 2011_Table_3-24.csv 2011
echo "TABLE 3-25: ESTIMATED NUMBER OF LIVESTOCK TREATED BY ZONE AND REGION"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-25.csv 132 133 tmpTable.csv 2011_Table_3-25.csv 2011
echo "TABLE 3-26a: ESTIMATED NUMBER OF LIVESTOCK DIED FROM DISEASE BY ZONE AND REGION"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-26a.csv 134 135 tmpTable.csv 2011_Table_3-26a.csv 2011
echo "TABLE 3-26b: ESTIMATED NUMBER OF LIVESTOCK DIED FROM OTHER CAUSES BY ZONE AND REGION"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-26b.csv 136 137 tmpTable.csv 2011_Table_3-26b.csv 2011
echo "TABLE 3-27a: NUMBER OF HOLDINGS BY SIZE OF CATTLE"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-27a.csv 138 139 tmpTable.csv 2011_Table_3-27a.csv 2011
echo "2011 Cattle tables complete"
