#
# Script to create all of the 2011 Sheep tables
#
# The Sheep tables are:
#    TABLE 3-1: NUMBER OF LIVESTOCK BY TYPE OF ANIMAL, ZONE, AND REGION
#    TABLE 3-3: NUMBER OF SHEEP BY AGE AND SEX OF ANIMAL, ZONE, AND REGION
#    TABLE 3-8: SHEEP AGED 2 YEARS AND OLDER BY SEX, PURPOSE, ZONE, AND REGION
#    TABLE 3-15 NUMBERS OF SHEEP BY SEX, BREED, ZONE, AND REGION
#    TABLE 3–19b: ESTIMATED NUMBERS OF BIRTHS, PURCHASES, AND ACQUIRED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Sheep
#    TABLE 3–20b: ESTIMATED NUMBERS OF SALES, SLAUGHTERS, DEATHS, AND OFFERED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Sheep
#    TABLE 3-23b: ESTIMATED NUMBER OF VACCINATED LIVESTOCK BY ZONE AND REGION - Sheep
#    TABLE 3-24: ESTIMATED NUMBER OF LIVESTOCK AFFLICTED/DISEASED BY ZONE AND REGION
#    TABLE 3-25: ESTIMATED NUMBER OF LIVESTOCK TREATED BY ZONE AND REGION
#    TABLE 3-26a: ESTIMATED NUMBER OF LIVESTOCK DIED FROM DISEASE BY ZONE AND REGION
#    TABLE 3-26b: ESTIMATED NUMBER OF LIVESTOCK DIED FROM OTHER CAUSES BY ZONE AND REGION
#    TABLE 3-27b: NUMBER OF HOLDINGS BY SIZE OF SHEEP
#
# echo "TABLE 3-1: NUMBER OF LIVESTOCK BY TYPE OF ANIMAL, ZONE, AND REGION"
# ./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-1.csv 40 41 tmpTable.csv 2011_Table_3-1.csv 2011
echo "TABLE 3-3: NUMBER OF SHEEP BY AGE AND SEX OF ANIMAL, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-3.csv 44 45 tmpTable.csv 2011_Table_3-3.csv 2011
echo "TABLE 3-8: SHEEP AGED 2 YEARS AND OLDER BY SEX, PURPOSE, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-8.csv 54 55 tmpTable.csv 2011_Table_3-8.csv 2011
echo "TABLE 3-15 NUMBERS OF SHEEP BY SEX, BREED, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-15.csv 68 69 tmpTable.csv 2011_Table_3-15.csv 2011
echo "TABLE 3–19b: ESTIMATED NUMBERS OF BIRTHS, PURCHASES, AND ACQUIRED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Sheep"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-19b.csv 84 85 tmpTable.csv 2011_Table_3-19b.csv 2011
echo "TABLE 3–20b: ESTIMATED NUMBERS OF SALES, SLAUGHTERS, DEATHS, AND OFFERED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Sheep"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-20b.csv 100 101 tmpTable.csv 2011_Table_3-20b.csv 2011
echo "TABLE 3-23b: ESTIMATED NUMBER OF VACCINATED LIVESTOCK BY ZONE AND REGION - Sheep"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-23b.csv 124 125 tmpTable.csv 2011_Table_3-23b.csv 2011
# echo "TABLE 3-24: ESTIMATED NUMBER OF LIVESTOCK AFFLICTED/DISEASED BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-24.csv 130 131 tmpTable.csv 2011_Table_3-24.csv 2011
# echo "TABLE 3-25: ESTIMATED NUMBER OF LIVESTOCK TREATED BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-25.csv 132 133 tmpTable.csv 2011_Table_3-25.csv 2011
# echo "TABLE 3-26a: ESTIMATED NUMBER OF LIVESTOCK DIED FROM DISEASE BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-26a.csv 134 135 tmpTable.csv 2011_Table_3-26a.csv 2011
# echo "TABLE 3-26b: ESTIMATED NUMBER OF LIVESTOCK DIED FROM OTHER CAUSES BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-26b.csv 136 137 tmpTable.csv 2011_Table_3-26b.csv 2011
echo "TABLE 3-27b: NUMBER OF HOLDINGS BY SIZE OF SHEEP"
./pdfETHCSApipeline.sh 2011-Livestock.pdf pages.pdf table3-27b.csv 140 141 tmpTable.csv 2011_Table_3-27b.csv 2011
echo "2011 Sheep tables complete"
