#
# Script to create all of the 2008 Sheep tables
#
# The Sheep tables are:
#    TABLE 3-1: NUMBER OF LIVESTOCK BY TYPE OF ANIMAL, ZONE, AND REGION
#    TABLE 3-3: NUMBER OF SHEEP BY AGE AND SEX OF ANIMAL, ZONE, AND REGION
#    TABLE 3-8: SHEEP AGED 2 YEARS AND OLDER BY SEX, PURPOSE, ZONE, AND REGION
#    TABLE 3-15 NUMBERS OF SHEEP BY SEX, BREED, ZONE, AND REGION
#    TABLE 3–19b: ESTIMATED NUMBERS OF BIRTHS, PURCHASES, AND ACQUIRED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Sheep
#    TABLE 3–20b: ESTIMATED NUMBERS OF SALES, SLAUGHTERS, DEATHS, AND OFFERED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Sheep
#    TABLE 3-23b: ESTIMATED NUMBER OF VACCINATED LIVESTOCK BY ZONE AND REGION - Sheep
#    TABLE 3-24: ESTIMATED NUMBER OF LIVESTOCK AFFLICTED/DISEASED BY ZONE AND REGION
#    TABLE 3-25: ESTIMATED NUMBER OF LIVESTOCK TREATED BY ZONE AND REGION
#    TABLE 3-26a: ESTIMATED NUMBER OF LIVESTOCK DIED FROM DISEASE BY ZONE AND REGION
#    TABLE 3-26b: ESTIMATED NUMBER OF LIVESTOCK DIED FROM OTHER CAUSES BY ZONE AND REGION
#    TABLE 3-27b: NUMBER OF HOLDINGS BY SIZE OF SHEEP
#
echo "TABLE 3-1: NUMBER OF LIVESTOCK BY TYPE OF ANIMAL, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2008-Livestock.pdf pages.pdf table3-1.csv 39 40 tmpTable.csv 2008_Table_3-1.csv 2008
echo "TABLE 3-3: NUMBER OF SHEEP BY AGE AND SEX OF ANIMAL, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2008-Livestock.pdf pages.pdf table3-3.csv 43 44 tmpTable.csv 2008_Table_3-3.csv 2008
echo "TABLE 3-8: SHEEP AGED 2 YEARS AND OLDER BY SEX, PURPOSE, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2008-Livestock.pdf pages.pdf table3-8.csv 53 54 tmpTable.csv 2008_Table_3-8.csv 2008
echo "TABLE 3-15 NUMBERS OF SHEEP BY SEX, BREED, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2008-Livestock.pdf pages.pdf table3-15.csv 67 68 tmpTable.csv 2008_Table_3-15.csv 2008
echo "TABLE 3–19b: ESTIMATED NUMBERS OF BIRTHS, PURCHASES, AND ACQUIRED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Sheep"
./pdfETHCSApipeline.sh 2008-Livestock.pdf pages.pdf table3-19b.csv 83 84 tmpTable.csv 2008_Table_3-19b.csv 2008
echo "TABLE 3–20b: ESTIMATED NUMBERS OF SALES, SLAUGHTERS, DEATHS, AND OFFERED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Sheep"
./pdfETHCSApipeline.sh 2008-Livestock.pdf pages.pdf table3-20b.csv 99 100 tmpTable.csv 2008_Table_3-20b.csv 2008
echo "TABLE 3-23b: ESTIMATED NUMBER OF VACCINATED LIVESTOCK BY ZONE AND REGION - Sheep"
./pdfETHCSApipeline.sh 2008-Livestock.pdf pages.pdf table3-23b.csv 123 124 tmpTable.csv 2008_Table_3-23b.csv 2008
echo "TABLE 3-24: ESTIMATED NUMBER OF LIVESTOCK AFFLICTED/DISEASED BY ZONE AND REGION"
./pdfETHCSApipeline.sh 2008-Livestock.pdf pages.pdf table3-24.csv 129 130 tmpTable.csv 2008_Table_3-24.csv 2008
echo "TABLE 3-25: ESTIMATED NUMBER OF LIVESTOCK TREATED BY ZONE AND REGION"
./pdfETHCSApipeline.sh 2008-Livestock.pdf pages.pdf table3-25.csv 131 132 tmpTable.csv 2008_Table_3-25.csv 2008
echo "TABLE 3-26a: ESTIMATED NUMBER OF LIVESTOCK DIED FROM DISEASE BY ZONE AND REGION"
./pdfETHCSApipeline.sh 2008-Livestock.pdf pages.pdf table3-26a.csv 133 134 tmpTable.csv 2008_Table_3-26a.csv 2008
echo "TABLE 3-26b: ESTIMATED NUMBER OF LIVESTOCK DIED FROM OTHER CAUSES BY ZONE AND REGION"
./pdfETHCSApipeline.sh 2008-Livestock.pdf pages.pdf table3-26b.csv 135 136 tmpTable.csv 2008_Table_3-26b.csv 2008
echo "TABLE 3-27b: NUMBER OF HOLDINGS BY SIZE OF SHEEP"
./pdfETHCSApipeline.sh 2008-Livestock.pdf pages.pdf table3-27b.csv 139 140 tmpTable.csv 2008_Table_3-27b.csv 2008
echo "2008 Sheep tables complete"
