#
# Script to create all of the 2013 Camels tables
#
# The Camels tables are:
#    TABLE 3-1: NUMBER OF LIVESTOCK BY TYPE OF ANIMAL, ZONE, AND REGION
#    TABLE 3-6: NUMBER OF MULES AND CAMELS BY AGE AND SEX OF ANIMAL, ZONE, AND REGION
#    TABLE 3-13: CAMELS AGED 4 YEARS AND OLDER BY SEX, PURPOSE, ZONE, AND REGION
#    TABLE 3–19g: ESTIMATED NUMBERS OF BIRTHS, PURCHASES, AND ACQUIRED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Camels
#    TABLE 3–20g: ESTIMATED NUMBERS OF SALES, SLAUGHTERS, DEATHS, AND OFFERED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Camels
#    TABLE 3-21: NUMBER OF DAIRY ANIMALS, MILK PRODUCTION, AND LACTATION PERIOD BY ZONE AND REGION
#    TABLE 3-23d: ESTIMATED NUMBER OF VACCINATED LIVESTOCK BY ZONE AND REGION - Camels
#    TABLE 3-24: ESTIMATED NUMBER OF LIVESTOCK AFFLICTED/DISEASED BY ZONE AND REGION
#    TABLE 3-25: ESTIMATED NUMBER OF LIVESTOCK TREATED BY ZONE AND REGION
#    TABLE 3-26a: ESTIMATED NUMBER OF LIVESTOCK DIED FROM DISEASE BY ZONE AND REGION
#    TABLE 3-26b: ESTIMATED NUMBER OF LIVESTOCK DIED FROM OTHER CAUSES BY ZONE AND REGION
#    TABLE 3-27e: NUMBER OF HOLDINGS BY SIZES OF MULES AND CAMELS
#
# echo "TABLE 3-1: NUMBER OF LIVESTOCK BY TYPE OF ANIMAL, ZONE, AND REGION"
# ./pdfETHCSApipeline.sh 2013-Livestock.pdf pages.pdf table3-1.csv 44 45 tmpTable.csv 2013_Table_3-1.csv 2013
echo "TABLE 3-6: NUMBER OF MULES AND CAMELS BY AGE AND SEX OF ANIMAL, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2013-Livestock.pdf pages.pdf table3-6.csv 54 55 tmpTable.csv 2013_Table_3-6.csv 2013
echo "TABLE 3-13: CAMELS AGED 4 YEARS AND OLDER BY SEX, PURPOSE, ZONE, AND REGION"
./pdfETHCSApipeline.sh 2013-Livestock.pdf pages.pdf table3-13.csv 68 69 tmpTable.csv 2013_Table_3-13.csv 2013
echo "TABLE 3–19g: ESTIMATED NUMBERS OF BIRTHS, PURCHASES, AND ACQUIRED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Camels"
./pdfETHCSApipeline.sh 2013-Livestock.pdf pages.pdf table3-19g.csv 98 99 tmpTable.csv 2013_Table_3-19g.csv 2013
echo "TABLE 3–20g: ESTIMATED NUMBERS OF SALES, SLAUGHTERS, DEATHS, AND OFFERED ANIMALS DURING THE REFERENCE PERIOD BY ZONE AND REGION - Camels"
./pdfETHCSApipeline.sh 2013-Livestock.pdf pages.pdf table3-20g.csv 114 115 tmpTable.csv 2013_Table_3-20g.csv 2013
# echo "TABLE 3-21: NUMBER OF DAIRY ANIMALS, MILK PRODUCTION, AND LACTATION PERIOD BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2013-Livestock.pdf pages.pdf table3-21.csv 118 119 tmpTable.csv 2013_Table_3-21.csv 2013
echo "TABLE 3-23d: ESTIMATED NUMBER OF VACCINATED LIVESTOCK BY ZONE AND REGION - Camels"
./pdfETHCSApipeline.sh 2013-Livestock.pdf pages.pdf table3-23d.csv 132 133 tmpTable.csv 2013_Table_3-23d.csv 2013
# echo "TABLE 3-24: ESTIMATED NUMBER OF LIVESTOCK AFFLICTED/DISEASED BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2013-Livestock.pdf pages.pdf table3-24.csv 134 135 tmpTable.csv 2013_Table_3-24.csv 2013
# echo "TABLE 3-25: ESTIMATED NUMBER OF LIVESTOCK TREATED BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2013-Livestock.pdf pages.pdf table3-25.csv 136 137 tmpTable.csv 2013_Table_3-25.csv 2013
# echo "TABLE 3-26a: ESTIMATED NUMBER OF LIVESTOCK DIED FROM DISEASE BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2013-Livestock.pdf pages.pdf table3-26a.csv 138 139 tmpTable.csv 2013_Table_3-26a.csv 2013
# echo "TABLE 3-26b: ESTIMATED NUMBER OF LIVESTOCK DIED FROM OTHER CAUSES BY ZONE AND REGION"
# ./pdfETHCSApipeline.sh 2013-Livestock.pdf pages.pdf table3-26b.csv 140 141 tmpTable.csv 2013_Table_3-26b.csv 2013
echo "TABLE 3-27e: NUMBER OF HOLDINGS BY SIZES OF MULES AND CAMELS"
./pdfETHCSApipeline.sh 2013-Livestock.pdf pages.pdf table3-27e.csv 150 151 tmpTable.csv 2013_Table_3-27e.csv 2013
echo "2013 Camels tables complete"
